apiVersion: v1
kind: Pod 
metadata: 
  name: my-pod-1
  labels:
    app: my-app
    env: prod
  namespace: production

spec:
  containers:
  - name: my-nginx
    image: nginx
    ports:
    - name: http
      containerPort: 80

  - name: my-tomcat
    image: tomcat 
    ports:
    - name: http
      containerPort: 8080
