---
apiVersion: v1
kind: Pod
metadata:
  name: my-demo-pod
  labels:
    env: prod-env
    app: my-demo-pod
  namespace: production
spec:
  containers:
    - name: nginx-instance
      image: nginx
      ports:
        - name: http
          containerPort: 80
    - name: tomcat-instance
      image: tomcat
      ports:
        - name: java
          containerPort: 8080
