---
apiVersion: v1
kind: Service
metadata:
  name: eb-ms-pod-service
  labels:
    env: UAT-env
    app: eb-ms-app
  namespace: uat
spec:
  type: NodePort
  selector:
    app: my-pod-1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: httpp
      protocol: TCP
      port: 8080
      targetPort: 8080