---
apiVersion: v1
kind: Service
metadata:
  name: my-demo-pod
  labels:
    env: prod-env
    app: my-demo-pod 
  namespace: production #mention name space name which is  already created
spec:
  type: NodePort
  selector:
    app: my-demo-pod # production madle labels madle envoirnment variable chi name ahe ethe [app: eb-ms-app]
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: httpp
      protocol: TCP
      port: 8080
      targetPort: 8080
