apiVersion: v1
kind: Service
metadata: 
    name: nginx-svc
    labels:
      env: prod
    namespace: production
spec:
  type: NodePort
  selector: 
    app: my-pod-1
  ports:
  - name: http
    protocol: TCP 
    port: 80
    targetPort: 90